site_name: spatial-spur
site_url: https://spatial-spur.github.io/
repo_url: https://github.com/spatial-spur/spatial-spur.github.io
repo_name: spatial-spur/spatial-spur.github.io

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue-grey
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue-grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - awesome-pages

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/simulation.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - tables
  - toc:
      permalink: true
